- name: Deploy Python App
  hosts: all
  become: true
  roles:
    - name: web_app
      tags: [web_app]
      vars:
        app_image_name: soralin/moscow-time-webapp
        app_tag: latest

        app_name: app_python
        app_path: app_python

        app_internal_port: 5000
        app_external_port: 8000

        app_wipe: false