apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-python
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: app-python
    spec:
      containers:
      - name: moscow-time-webapp
        image: soralin/moscow-time-webapp:latest
        ports:
        - containerPort: 5000